### PR TITLE
suggestions fixed

### PR DESCRIPTION
**Pull request by HugoWith**
Please check if the PR fulfills these requirements
 The commit message follows our guidelines
 Tests for the changes have been added (for bug fixes / features)
 Docs have been added / updated (for bug fixes / features)
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
👉 Fix Suggestions. It now, evolve with the query

What is the current behavior? (You can also link to an open issue here)
👉 Suggestions broken

What is the new behavior (if this is a feature change)?
👉  Evolve with the query 
👉  Don't show a suggestions that is the same than the query or the category page

Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
👉 NO
Other information:

### CODE REVIEW

**Comment by guiMendel** [comment]
you can delete the previous code no problem 🙃

**Comment by HugoWith** [comment]
Not sure if it's more efficient though ... 😕 
I'd like to keep your code just in case. If you're okay with that ? 😊  @guiMendel

**Review by matthew1809 — CHANGES_REQUESTED** [review]
LGTM, let's remove any commented code though, unless valid reason?

**Comment by HugoWith** [comment]
As you want guys 😊
It's removed

**Review by matthew1809 — APPROVED** [review]

**Pull request merged**
